Fabulous graphics toggle - Sodium edition
IrisShaders/sodium-fabric pull request #15
Opened 2021-06-12 01:07 UTC by IMS212

A bit hacky, but seems to work well.

2021-07-28 16:55 UTC, coderbot16 requested changes
There's a lot of code duplicated between these code paths - deduplicating them would be preferable.

2021-07-31 22:30 UTC, IMS212 commented
The code here is quite messy, however it's been deduplicated.

2021-08-26 01:25 UTC, coderbot16 approved these changes
One whitespace change, otherwise looks good to me.

2021-08-26 01:25 UTC, coderbot16 commented on src/main/java/me/jellysquid/mods/sodium/client/gui/SodiumGameOptionPages.java
> +        if(!Iris.getIrisConfig().areShadersEnabled() && GlStateManager.supportsGl30()) {
```suggestion
        if (!Iris.getIrisConfig().areShadersEnabled() && GlStateManager.supportsGl30()) {
```

2021-08-26 01:25 UTC, merged